CLI fixes for BN
shardeum/shardeum-validator-cli pull request #15
Opened 2024-07-11 04:48 UTC by Glitch18

The status command is broken and needs fixes for how values are handled.

2024-07-11 14:22 UTC, mssabr01 requested changes, later dismissed

2024-07-11 14:22 UTC, mssabr01 commented on src/node-commands.ts
> +                  String(parseInt(eoaData.operatorAccountInfo.stake.value, 16))
What happens if stake and value do not exist on this object?

2024-07-11 14:22 UTC, mssabr01 commented on src/utils/fetch-network-data.ts
> +      ),
Same here. nodeRewardAmount might not exist

2024-07-11 14:22 UTC, mssabr01 commented on src/utils/fetch-network-data.ts
> +  const nodeRewardInterval = new BN(response.nodeRewardInterval);
Catch if nodeRewardAmountUsd and nodeRewardInterval does not exist

2024-07-11 14:22 UTC, mssabr01 commented on src/utils/fetch-network-data.ts
> +    params.lockedStake = new BN(
Please check that stakeLock is present

2024-07-13 00:23 UTC, ahmxdiqbal commented on src/node-commands.ts
> +                  String(parseInt(eoaData.operatorAccountInfo.stake.value, 16))
its wrapped in a try catch, so it would've just console logged the error. now it should just use a empty string

2024-07-13 07:50 UTC, Glitch18 commented
@mssabr01 Changes by Ahmed look good. Let me know if there are any further changes required before this can be merged

2024-08-08 04:49 UTC, achal-singh approved these changes

2024-08-08 04:50 UTC, merged

2024-08-08 19:53 UTC, mssabr01 reviewed
lgtm